// Textes de la boîte à outils d'encodage (Base64, URL, hexadécimal, HTML, JWT, empreintes, horodatage, UUID) (FR/EN).
export const ENCODER = {
  fr: {
    ui: {
      meta: {
        title: 'Encodeur / décodeur : Base64, URL, JWT, hash, UUID | Guillaume Richard',
        description:
          "Encodez et décodez du Base64, des URL, de l'hexadécimal et des entités HTML ; lisez un JWT ; calculez MD5, SHA-1, SHA-256, SHA-512 d'un texte ou d'un fichier ; convertissez un timestamp ; générez des UUID. Dans votre navigateur.",
        appDescription:
          'Boîte à outils gratuite : Base64, URL, hexadécimal, HTML, JWT, empreintes de fichiers, horodatages et UUID, sans envoi de données.',
      },
      name: 'Encodeur / décodeur (Base64, JWT, hash…)',
      card: 'Base64, URL, hex, HTML, JWT, MD5/SHA, timestamps et UUID.',
      keywords:
        'base64 url encode decode jwt hash md5 sha256 sha1 timestamp epoch uuid hex html entites checksum empreinte',
      h1: 'Encodeur / décodeur',
      intro:
        "Huit outils de développeur et d'administrateur dans une page : encodage et décodage Base64, URL, hexadécimal et HTML, lecture d'un JWT, empreintes MD5 et SHA de textes ou de fichiers, conversion de timestamps et génération d'UUID. Tout est calculé dans votre navigateur.",
      tabs: {
        base64: 'Base64',
        url: 'URL',
        hex: 'Hexadécimal',
        html: 'HTML',
        jwt: 'JWT',
        hash: 'Empreintes',
        time: 'Timestamp',
        uuid: 'UUID',
      },
      tabsLabel: 'Outils',
      common: {
        input: 'Texte',
        output: 'Résultat',
        copy: 'Copier',
        copied: 'Copié',
        clear: 'Effacer',
        swap: 'Utiliser le résultat comme entrée',
        encode: 'Encoder',
        decode: 'Décoder',
        invalid: 'Entrée invalide pour ce décodage.',
        empty: 'Saisissez un texte.',
      },
      base64: {
        urlSafe: 'Variante URL-safe (- et _ à la place de + et /)',
        padding: 'Ajouter le remplissage « = »',
        binary:
          'Les octets décodés ne forment pas du texte UTF-8 : voici leur valeur hexadécimale.',
        detected: 'Base64 URL-safe détecté.',
      },
      url: {
        component: 'Composant (encodeURIComponent)',
        full: 'URL entière (encodeURI)',
        plus: 'Lire « + » comme une espace (formulaires)',
        parts: 'Décomposition',
        fields: {
          protocol: 'Protocole',
          host: 'Hôte',
          port: 'Port',
          path: 'Chemin',
          hash: 'Ancre',
          username: 'Utilisateur',
          password: 'Mot de passe',
          params: 'Paramètres',
        },
      },
      hex: {
        separator: 'Séparateur',
        none: 'aucun',
        space: 'espace',
        colon: 'deux-points',
        hint: 'Accepte 0x, espaces, « : », virgules et tirets.',
      },
      html: { escape: 'Échapper', unescape: 'Déséchapper' },
      jwt: {
        input: 'Jeton JWT',
        placeholder: 'eyJhbGciOiJIUzI1NiIs…',
        header: 'En-tête',
        payload: 'Charge utile',
        signature: 'Signature',
        claims: 'Revendications',
        statuses: {
          expired: 'Expiré',
          notYetValid: 'Pas encore valide',
          valid: 'Valide dans le temps',
          noExpiry: "Aucune date d'expiration (exp)",
        },
        notice:
          "Le jeton est seulement décodé : sa signature n'est PAS vérifiée (il faudrait la clé). Ne collez jamais ici un jeton de production encore valide si vous n'êtes pas à l'aise : tout reste dans votre navigateur, mais mieux vaut s'en passer.",
        unsigned:
          "Ce jeton n'est pas signé (alg « none » ou signature vide) : n'importe qui peut en forger un.",
        errors: {
          format: 'Un JWT comporte trois parties séparées par des points.',
          header: "L'en-tête n'est pas du JSON en Base64 URL valide.",
          payload: "La charge utile n'est pas du JSON en Base64 URL valide.",
        },
        labels: {
          issuer: 'émetteur (iss)',
          subject: 'sujet (sub)',
          audience: 'audience (aud)',
          expiration: 'expiration (exp)',
          notBefore: 'pas avant (nbf)',
          issuedAt: 'émis le (iat)',
          id: 'identifiant (jti)',
        },
      },
      hash: {
        text: 'Texte',
        file: 'Fichier',
        fileLabel: 'Choisir un fichier',
        compare: 'Empreinte attendue (pour comparer)',
        match: 'Identique : les empreintes correspondent.',
        noMatch: 'Différente : les empreintes ne correspondent pas.',
        algorithm: 'Algorithme',
        working: 'Calcul…',
        md5Warning:
          'MD5 et SHA-1 sont cassés contre un attaquant ; ils servent encore à détecter une corruption de fichier.',
      },
      time: {
        input: 'Timestamp ou date',
        placeholder: '1700000000 · 2025-01-15T10:30:00Z',
        now: 'Maintenant',
        units: {
          s: 'secondes',
          ms: 'millisecondes',
          us: 'microsecondes',
          ns: 'nanosecondes',
          date: 'date saisie',
        },
        rows: {
          seconds: 'Epoch (secondes)',
          milliseconds: 'Epoch (millisecondes)',
          iso: 'ISO 8601 (UTC)',
          utc: 'UTC',
          local: 'Heure locale',
          relative: 'Relatif',
          timeZone: 'Fuseau local',
        },
        detected: (unit: string) => `Interprété comme : ${unit}`,
        invalid: 'Ni un nombre, ni une date reconnue.',
      },
      uuid: {
        version: 'Version',
        v4: 'v4 (aléatoire)',
        v7: 'v7 (triable par date)',
        count: 'Nombre',
        generate: 'Générer',
        inspect: 'Analyser un UUID',
        inspectPlaceholder: '123e4567-e89b-12d3-a456-426614174000',
        rows: {
          version: 'Version',
          variant: 'Variante',
          canonical: 'Forme canonique',
          date: 'Date incorporée',
        },
        invalid: "Ce n'est pas un UUID valide.",
      },
      privacy:
        'Tout est calculé dans votre navigateur : textes, fichiers et jetons ne sont jamais envoyés.',
      seo: {
        whatTitle: "Ce que fait l'outil",
        what: [
          [
            'Encodages courants',
            "Base64 (classique et URL-safe, UTF-8 sûr), encodage d'URL avec décomposition des paramètres, hexadécimal et entités HTML.",
          ],
          [
            'Lecteur de JWT',
            "Décode l'en-tête et la charge utile, affiche les dates exp, nbf et iat, signale un jeton expiré ou non signé, sans jamais vérifier ni transmettre la signature.",
          ],
          [
            'Empreintes de texte et de fichiers',
            "MD5, SHA-1, SHA-256, SHA-384 et SHA-512, avec comparaison à l'empreinte attendue pour contrôler un téléchargement.",
          ],
          [
            'Horodatages et UUID',
            "Détecte secondes, millisecondes, microsecondes ou nanosecondes, convertit en ISO, UTC et heure locale ; génère des UUID v4 et v7 et analyse ceux qu'on lui donne.",
          ],
        ],
        howTitle: 'Comment l’utiliser',
        how: "Choisissez l'onglet de l'outil, collez le texte ou le jeton, ou déposez un fichier pour une empreinte : le résultat est immédiat et se copie en un clic.",
        faq: [
          [
            'Décoder un JWT, est-ce le valider ?',
            "Non. Un JWT se lit librement (ses parties sont du JSON en Base64 URL) ; seule la vérification de sa signature avec la clé prouve qu'il est authentique. Cet outil ne fait que le lire.",
          ],
          [
            'Pourquoi mon Base64 ne se décode-t-il pas ?',
            "Il peut contenir des caractères étrangers, ou une longueur impossible (un reste de 1 caractère). Les retours à la ligne et le « = » manquant sont tolérés ; mélanger « + / » et « - _ » ne l'est pas.",
          ],
          [
            'Comment vérifier un fichier téléchargé ?',
            "Calculez son SHA-256 dans l'onglet Empreintes et collez l'empreinte publiée par l'éditeur dans le champ de comparaison : l'outil dit si elles sont identiques.",
          ],
        ],
      },
      related: 'Voir aussi',
      relatedLinks: [],
    },
  },
  en: {
    ui: {
      meta: {
        title: 'Encoder / decoder: Base64, URL, JWT, hash, UUID | Guillaume Richard',
        description:
          'Encode and decode Base64, URLs, hexadecimal and HTML entities; read a JWT; compute MD5, SHA-1, SHA-256, SHA-512 of text or a file; convert a timestamp; generate UUIDs. In your browser.',
        appDescription:
          'Free toolbox: Base64, URL, hexadecimal, HTML, JWT, file hashes, timestamps and UUIDs, with no data upload.',
      },
      name: 'Encoder / decoder (Base64, JWT, hash…)',
      card: 'Base64, URL, hex, HTML, JWT, MD5/SHA, timestamps and UUIDs.',
      keywords:
        'base64 url encode decode jwt hash md5 sha256 sha1 timestamp epoch uuid hex html entities checksum',
      h1: 'Encoder / decoder',
      intro:
        'Eight developer and administrator tools in one page: Base64, URL, hexadecimal and HTML encoding and decoding, JWT reading, MD5 and SHA hashes of text or files, timestamp conversion and UUID generation. Everything is computed in your browser.',
      tabs: {
        base64: 'Base64',
        url: 'URL',
        hex: 'Hexadecimal',
        html: 'HTML',
        jwt: 'JWT',
        hash: 'Hashes',
        time: 'Timestamp',
        uuid: 'UUID',
      },
      tabsLabel: 'Tools',
      common: {
        input: 'Text',
        output: 'Result',
        copy: 'Copy',
        copied: 'Copied',
        clear: 'Clear',
        swap: 'Use the result as input',
        encode: 'Encode',
        decode: 'Decode',
        invalid: 'Invalid input for this decoding.',
        empty: 'Enter some text.',
      },
      base64: {
        urlSafe: 'URL-safe variant (- and _ instead of + and /)',
        padding: 'Add "=" padding',
        binary: 'The decoded bytes are not UTF-8 text: here is their hexadecimal value.',
        detected: 'URL-safe Base64 detected.',
      },
      url: {
        component: 'Component (encodeURIComponent)',
        full: 'Whole URL (encodeURI)',
        plus: 'Read "+" as a space (forms)',
        parts: 'Breakdown',
        fields: {
          protocol: 'Protocol',
          host: 'Host',
          port: 'Port',
          path: 'Path',
          hash: 'Fragment',
          username: 'User',
          password: 'Password',
          params: 'Parameters',
        },
      },
      hex: {
        separator: 'Separator',
        none: 'none',
        space: 'space',
        colon: 'colon',
        hint: 'Accepts 0x, spaces, ":", commas and dashes.',
      },
      html: { escape: 'Escape', unescape: 'Unescape' },
      jwt: {
        input: 'JWT',
        placeholder: 'eyJhbGciOiJIUzI1NiIs…',
        header: 'Header',
        payload: 'Payload',
        signature: 'Signature',
        claims: 'Claims',
        statuses: {
          expired: 'Expired',
          notYetValid: 'Not yet valid',
          valid: 'Valid in time',
          noExpiry: 'No expiry date (exp)',
        },
        notice:
          'The token is only decoded: its signature is NOT verified (that needs the key). Avoid pasting a still-valid production token here if you are not comfortable: everything stays in your browser, but it is better to do without.',
        unsigned: 'This token is unsigned (alg "none" or empty signature): anyone can forge one.',
        errors: {
          format: 'A JWT has three parts separated by dots.',
          header: 'The header is not valid Base64URL JSON.',
          payload: 'The payload is not valid Base64URL JSON.',
        },
        labels: {
          issuer: 'issuer (iss)',
          subject: 'subject (sub)',
          audience: 'audience (aud)',
          expiration: 'expiration (exp)',
          notBefore: 'not before (nbf)',
          issuedAt: 'issued at (iat)',
          id: 'identifier (jti)',
        },
      },
      hash: {
        text: 'Text',
        file: 'File',
        fileLabel: 'Choose a file',
        compare: 'Expected hash (to compare)',
        match: 'Identical: the hashes match.',
        noMatch: 'Different: the hashes do not match.',
        algorithm: 'Algorithm',
        working: 'Computing…',
        md5Warning:
          'MD5 and SHA-1 are broken against an attacker; they are still useful to detect file corruption.',
      },
      time: {
        input: 'Timestamp or date',
        placeholder: '1700000000 · 2025-01-15T10:30:00Z',
        now: 'Now',
        units: {
          s: 'seconds',
          ms: 'milliseconds',
          us: 'microseconds',
          ns: 'nanoseconds',
          date: 'entered date',
        },
        rows: {
          seconds: 'Epoch (seconds)',
          milliseconds: 'Epoch (milliseconds)',
          iso: 'ISO 8601 (UTC)',
          utc: 'UTC',
          local: 'Local time',
          relative: 'Relative',
          timeZone: 'Local time zone',
        },
        detected: (unit: string) => `Interpreted as: ${unit}`,
        invalid: 'Neither a number nor a recognised date.',
      },
      uuid: {
        version: 'Version',
        v4: 'v4 (random)',
        v7: 'v7 (time-sortable)',
        count: 'Count',
        generate: 'Generate',
        inspect: 'Inspect a UUID',
        inspectPlaceholder: '123e4567-e89b-12d3-a456-426614174000',
        rows: {
          version: 'Version',
          variant: 'Variant',
          canonical: 'Canonical form',
          date: 'Embedded date',
        },
        invalid: 'This is not a valid UUID.',
      },
      privacy: 'Everything is computed in your browser: texts, files and tokens are never sent.',
      seo: {
        whatTitle: 'What the tool does',
        what: [
          [
            'Common encodings',
            'Base64 (standard and URL-safe, UTF-8 safe), URL encoding with parameter breakdown, hexadecimal and HTML entities.',
          ],
          [
            'JWT reader',
            'Decodes the header and payload, shows the exp, nbf and iat dates, flags an expired or unsigned token, without ever verifying or transmitting the signature.',
          ],
          [
            'Text and file hashes',
            'MD5, SHA-1, SHA-256, SHA-384 and SHA-512, with comparison to the expected hash to check a download.',
          ],
          [
            'Timestamps and UUIDs',
            'Detects seconds, milliseconds, microseconds or nanoseconds, converts to ISO, UTC and local time; generates v4 and v7 UUIDs and inspects the ones you give it.',
          ],
        ],
        howTitle: 'How to use it',
        how: 'Pick the tool tab, paste the text or token, or drop a file for a hash: the result is instant and copies in one click.',
        faq: [
          [
            'Is decoding a JWT the same as validating it?',
            'No. A JWT can be read freely (its parts are Base64URL JSON); only verifying its signature with the key proves it is authentic. This tool only reads it.',
          ],
          [
            'Why will my Base64 not decode?',
            'It may contain foreign characters, or an impossible length (a remainder of 1 character). Line breaks and missing "=" are tolerated; mixing "+ /" and "- _" is not.',
          ],
          [
            'How do I verify a downloaded file?',
            'Compute its SHA-256 in the Hashes tab and paste the hash published by the vendor into the comparison field: the tool says whether they are identical.',
          ],
        ],
      },
      related: 'See also',
      relatedLinks: [],
    },
  },
};
